export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const ERROR_CLEAR = 'ERROR_CLEAR';

export const LOAD_USER_DATA = 'LOAD_USER_DATA';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUT_REDIRECT_PATH';

export const GET_ACCOUNTS_START = 'GET_ACCOUNTS_START';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAIL = 'GET_ACCOUNTS_FAIL';

export const CREATE_LIKE_START = 'CREATE_LIKE_START'
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS'
export const CREATE_LIKE_FAIL = 'CREATE_LIKE_FAIL'

export const DELETE_LIKE_START = 'DELETE_LIKE_START'
export const DELETE_LIKE_SUCCESS = 'DELETE_LIKE_SUCCESS'
export const DELETE_LIKE_FAIL = 'DELETE_LIKE_FAIL'






